ft_estimation_node:
  ros__parameters:
    topic_raw_wrench: raw_wrench
    topic_joint_state: joint_states
    topic_estimated_wrench: ft_sensor_wrench
    topic_interaction_wrench: ft_interaction_wrench

    calibration:
      reference_frame:
        id: base_link
      sensor_frame:
        id: ft_sensor
      gravity_in_reference_frame: [0.0, 0.0, -9.81]
      calibration_filename: calibration_parameters.yaml
      calibration_package: ft_tools

    estimation:
      interaction_frame:
        id: tool0
      cutoff_frequency: 40.0
      wrench_deadband:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      base: base_link
      tip: tool0
      alpha: 0.0005
