name: CI (humble)
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@v0.3
        # continue-on-error: true
        with:
          target-ros2-distro: humble